<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>nls</string>
    <string>nlf</string>
  </array>
  <key>name</key>
  <string>Nelson</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#function</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#blocks</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#constants_override</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#brackets</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#curlybrackets</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#parens</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#string</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#transpose</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#double_quote</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#operators</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#builtin_keywords</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#number</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#variable</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#variable_invalid</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#not_equal_invalid</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#variable_assignment</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>blocks</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(^\s*)(for)\s+</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>meta.for-quantity.nelson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.for.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\s*(end)\b</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.end.for.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.for.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>\G(?!$)</string>
              <key>end</key>
              <string>$\n?</string>
              <key>name</key>
              <string>meta.for-quantity.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*)(parfor)\s+</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>meta.parfor-quantity.nelson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.for.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\s*(end)\b</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.end.for.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.parfor.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>\G(?!$)</string>
              <key>end</key>
              <string>$\n?</string>
              <key>name</key>
              <string>meta.parfor-quantity.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*)(if)\s+</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>meta.if-condition.nelson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.if.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\s*(end)\b</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.end.if.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.if.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>\G(?!$)</string>
              <key>end</key>
              <string>$\n?</string>
              <key>name</key>
              <string>meta.if-condition.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>meta.elseif-condition.nelson</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>keyword.control.elseif.nelson</string>
                </dict>
                <key>3</key>
                <dict>
                  <key>patterns</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>$self</string>
                    </dict>
                  </array>
                </dict>
              </dict>
              <key>end</key>
              <string>^</string>
              <key>match</key>
              <string>(^\s*)(elseif)\s+(.*)$\n?</string>
              <key>name</key>
              <string>meta.elseif.nelson</string>
            </dict>
            <dict>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>meta.else-condition.nelson</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>keyword.control.else.nelson</string>
                </dict>
              </dict>
              <key>end</key>
              <string>^</string>
              <key>match</key>
              <string>(^\s*)(else)\s+$\n?</string>
              <key>name</key>
              <string>meta.else.nelson</string>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*)(while)\s+</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>meta.while-condition.nelson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.while.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\s*(end)\b</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.end.while.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.while.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>\G(?!$)</string>
              <key>end</key>
              <string>$\n?</string>
              <key>name</key>
              <string>meta.while-condition.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*)(switch)\s+</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>meta.switch-expression.nelson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.switch.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\s*(end)\b</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.end.switch.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.switch.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>\G(?!$)</string>
              <key>end</key>
              <string>$\n?</string>
              <key>name</key>
              <string>meta.switch-expression.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>include</key>
                  <string>$self</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>meta.case-expression.nelson</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>keyword.control.case.nelson</string>
                </dict>
                <key>3</key>
                <dict>
                  <key>patterns</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>$self</string>
                    </dict>
                  </array>
                </dict>
              </dict>
              <key>end</key>
              <string>^</string>
              <key>match</key>
              <string>(^\s*)(case)\s+(.*)$\n?</string>
              <key>name</key>
              <string>meta.case.nelson</string>
            </dict>
            <dict>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>meta.otherwise-expression.nelson</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>keyword.control.otherwise.nelson</string>
                </dict>
              </dict>
              <key>end</key>
              <string>^</string>
              <key>match</key>
              <string>(^\s*)(otherwise)\s+$\n?</string>
              <key>name</key>
              <string>meta.otherwise.nelson</string>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*)(try)\s*($\n?|%)</string>
          <key>beginCaptures</key>
          <dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.try.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>^\s*(end)\b</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.end.try.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.try.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>meta.catch-exception.nelson</string>
                </dict>
                <key>2</key>
                <dict>
                  <key>name</key>
                  <string>keyword.control.catch.nelson</string>
                </dict>
                <key>3</key>
                <dict>
                  <key>patterns</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>$self</string>
                    </dict>
                  </array>
                </dict>
              </dict>
              <key>end</key>
              <string>^</string>
              <key>match</key>
              <string>(^\s*)(catch)(\s+.*)$\n?</string>
              <key>name</key>
              <string>meta.catch.nelson</string>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>brackets</key>
    <dict>
      <key>begin</key>
      <string>\[</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>meta.brackets.nelson</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>meta.brackets.nelson</string>
      <key>end</key>
      <string>\]</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>meta.brackets.nelson</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>builtin_keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#keywords</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#contants</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#variables</string>
        </dict>
      </array>
      <key>repository</key>
      <dict>
        <key>contants</key>
        <dict>
          <key>comment</key>
          <string>nelson constants</string>
          <key>match</key>
          <string>(?&lt;!\.)\b(eps|false|Inf|inf|intmax|intmin|namelengthmax|NaN|nan|on|off|realmax|realmin|true)\b</string>
          <key>name</key>
          <string>constant.language.nelson</string>
        </dict>
        <key>keywords</key>
        <dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>comment</key>
              <string>Control keywords</string>
              <key>match</key>
              <string>(?&lt;!\.)\b(break|case|catch|continue|else|elseif|end|enfunction|for|parfor|if|otherwise|pause|rethrow|return|stop|switch|try|while)\b</string>
              <key>name</key>
              <string>keyword.control.nelson</string>
            </dict>
          </array>
        </dict>
        <key>variables</key>
        <dict>
          <key>comment</key>
          <string>nelson variables</string>
          <key>match</key>
          <string>(?&lt;!\.)\b(nargin|nargout|varargin|varargout)\b</string>
          <key>name</key>
          <string>variable.other.function.nelson</string>
        </dict>
      </dict>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(^[ \t]+)?(?=%%)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.whitespace.comment.leading.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?!\G)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>%%</string>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.definition.comment.nelson</string>
                </dict>
              </dict>
              <key>end</key>
              <string>\n</string>
              <key>name</key>
              <string>comment.line.double-percentage.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>begin</key>
                  <string>\G\s*(?![\n\s])</string>
                  <key>contentName</key>
                  <string>meta.cell.nelson</string>
                  <key>end</key>
                  <string>(?=\n)</string>
                </dict>
              </array>
            </dict>
						<dict>
              <key>begin</key>
              <string>//</string>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.definition.comment.nelson</string>
                </dict>
              </dict>
              <key>end</key>
              <string>\n</string>
              <key>name</key>
              <string>comment.line.double-percentage.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>begin</key>
                  <string>\G\s*(?![\n\s])</string>
                  <key>contentName</key>
                  <string>meta.cell.nelson</string>
                  <key>end</key>
                  <string>(?=\n)</string>
                </dict>
              </array>
            </dict>
          </array>
        </dict>

        <dict>
          <key>begin</key>
          <string>%\{</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>%\}\s*\n</string>
          <key>name</key>
          <string>comment.block.percentage.nelson</string>
        </dict>

        <dict>
          <key>begin</key>
          <string>(^[ \t]+)?(?=%)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.whitespace.comment.leading.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?!\G)</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>%</string>
              <key>beginCaptures</key>
              <dict>
                <key>0</key>
                <dict>
                  <key>name</key>
                  <string>punctuation.definition.comment.nelson</string>
                </dict>
              </dict>
              <key>end</key>
              <string>\n</string>
              <key>name</key>
              <string>comment.line.percentage.nelson</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>constants_override</key>
    <dict>
      <key>comment</key>
      <string>Trying to override nelson constants and functions.</string>
      <key>match</key>
      <string>(^|\;)\s*(i|j|inf|Inf|nan|NaN|eps|end)\s*=[^=]</string>
      <key>name</key>
      <string>meta.inappropriate.nelson</string>
    </dict>
    <key>curlybrackets</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>meta.brackets.curly.nelson</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>meta.brackets.curly.nelson</string>
      <key>end</key>
      <string>\}</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>meta.brackets.curly.nelson</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#end_in_parens</string>
        </dict>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>double_quote</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>"</string>
          <key>name</key>
          <string>invalid.illegal.invalid-quote.nelson</string>
        </dict>
      </array>
    </dict>
    <key>end_in_parens</key>
    <dict>
      <key>comment</key>
      <string>end as operator symbol</string>
      <key>match</key>
      <string>\bend\b</string>
      <key>name</key>
      <string>keyword.operator.symbols.nelson</string>
    </dict>
    <key>function</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?x)
            (^\s*)                # Leading whitespace
            (function)
            \s+
            (?:                 # Optional
              (?:
                (\[) ([^\]]*) (\])
                | ([a-zA-Z_]\w*)
              )
              \s* = \s*
            )?
            ([a-zA-Z_]\w*)            # Function name
            \s*                 # Trailing space
          </string>
          <key>beginCaptures</key>
          <dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.begin.nelson</string>
            </dict>
            <key>3</key>
            <dict>
              <key>patterns</key>
              <array>
                <dict>
                  <key>match</key>
                  <string>\w+</string>
                  <key>name</key>
                  <string>variable.parameter.output.nelson</string>
                </dict>
              </array>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.arguments.end.nelson</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.output.function.nelson</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.nelson</string>
            </dict>
          </dict>
          <key>endfunction</key>
          <string>^\s*(endfunction)\b(\s*\n)?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.end.function.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>meta.function.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>begin</key>
              <string>\G\(</string>
              <key>end</key>
              <string>\)</string>
              <key>name</key>
              <string>meta.arguments.function.nelson</string>
              <key>patterns</key>
              <array>
                <dict>
                  <key>match</key>
                  <string>\w+</string>
                  <key>name</key>
                  <string>variable.parameter.input.nelson</string>
                </dict>
              </array>
            </dict>
            <dict>
              <key>include</key>
              <string>$self</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>not_equal_invalid</key>
    <dict>
      <key>comment</key>
      <string>Not equal is written ~= not !=.</string>
      <key>match</key>
      <string>\s*!=\s*</string>
      <key>name</key>
      <string>invalid.illegal.invalid-inequality.nelson</string>
    </dict>
    <key>number</key>
    <dict>
      <key>comment</key>
      <string>Valid numbers: 1, .1, 1.1, .1e1, 1.1e1, 1e1, 1i, 1j, 1e2j</string>
      <key>match</key>
      <string>(?&lt;=[\s\-\+\*\/\\=:\[\(\{,]|^)\d*\.?\d+([eE][+-]?\d)?([0-9&amp;&amp;[^\.]])*(i|j)?\b</string>
      <key>name</key>
      <string>constant.numeric.nelson</string>
    </dict>
    <key>operators</key>
    <dict>
      <key>comment</key>
      <string>Operator symbols</string>
      <key>match</key>
      <string>(?&lt;=\s)(==|~=|&gt;|&gt;=|&lt;|&lt;=|&amp;|&amp;&amp;|:|\||\|\||\+|-|\*|\.\*|/|\./|\\|\.\\|\^|\.\^)(?=\s)</string>
      <key>name</key>
      <string>keyword.operator.symbols.nelson</string>
    </dict>
    <key>parens</key>
    <dict>
      <key>begin</key>
      <string>\(</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>meta.parens.nelson</string>
        </dict>
      </dict>
      <key>contentName</key>
      <string>meta.parens.nelson</string>
      <key>end</key>
      <string>\)</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>meta.parens.nelson</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#end_in_parens</string>
        </dict>
        <dict>
          <key>include</key>
          <string>$self</string>
        </dict>
      </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.interpolated.nelson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.nelson</string>
            </dict>
          </dict>
          <key>comment</key>
          <string>Shell command</string>
          <key>match</key>
          <string>^\s*((!).*$\n?)</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>((?&lt;=(\[|\(|\{|=|\s|;|:|,))|^)'</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.nelson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>'(?=(\]|\)|\}|=|~|&lt;|&gt;|&amp;|\||-|\+|\*|\.|\^|\||\s|;|:|,))</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.nelson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.single.nelson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>match</key>
              <string>''</string>
              <key>name</key>
              <string>constant.character.escape.nelson</string>
            </dict>
            <dict>
              <key>match</key>
              <string>'(?=.)</string>
              <key>name</key>
              <string>invalid.illegal.unescaped-quote.nelson</string>
            </dict>
            <dict>
              <key>comment</key>
              <string>Operator symbols</string>
              <key>match</key>
              <string>((\%([\+\-0]?\d{0,3}(\.\d{1,3})?)(c|d|e|E|f|g|G|s|((b|t)?(o|u|x|X))))|\%\%|\\(b|f|n|r|t|\\))</string>
              <key>name</key>
              <string>constant.character.escape.nelson</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>transpose</key>
    <dict>
      <key>match</key>
      <string>((\w+)|(?&lt;=\])|(?&lt;=\)))\.?'</string>
      <key>name</key>
      <string>keyword.operator.transpose.nelson</string>
    </dict>
    <key>variable</key>
    <dict>
      <key>comment</key>
      <string>Valid variable. Added meta to disable hilightinh</string>
      <key>match</key>
      <string>\b[a-zA-Z]\w*\b</string>
      <key>name</key>
      <string>meta.variable.other.valid.nelson</string>
    </dict>
    <key>variable_assignment</key>
    <dict>
      <key>comment</key>
      <string>Incomplete variable assignment.</string>
      <key>match</key>
      <string>=\s*\.{0,2}\s*;?\s*$\n?</string>
      <key>name</key>
      <string>invalid.illegal.incomplete-variable-assignment.nelson</string>
    </dict>
    <key>variable_invalid</key>
    <dict>
      <key>comment</key>
      <string>No variables or function names can start with a number or an underscore.</string>
      <key>match</key>
      <string>\b(_\w|\d+[_a-df-zA-DF-Z])\w*\b</string>
      <key>name</key>
      <string>invalid.illegal.invalid-variable-name.nelson</string>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.nelson</string>
  <key>uuid</key>
  <string>45D5A2E4-F2F3-4144-B8D4-3D60DCEB3D05</string>
</dict>
</plist>